### PR TITLE
README: fix broken json in example config

### PR DESCRIPTION
**Pull request by fabridamicelli**
Current example config is broken json, so one cannot copy-paste it and get it working. This PR fixes json making it work out-of-the box

### CODE REVIEW

**Comment by minodisk** [comment]
@fabridamicelli 

Thanks for the PR.
But the README.md you fixed is generative, so I need you to edit the template, [README.md.ejs](https://github.com/minodisk/bigquery-runner/blob/250e340f57d03275b7d2d766197128af595a8431/packages/codegen/src/README.md.ejs). Otherwise your contribution history will be lost from the file.

**Comment by fabridamicelli** [comment]
@minodisk 
Thanks for the swift reaction.

I just fixed the commit with the change only in README.md.ejs. Hope that works?

**Comment by minodisk** [comment]
@fabridamicelli 
Thank you! Perfect!

**Comment by minodisk** [comment]
@fabridamicelli 
Published as [v1.21.12](https://marketplace.visualstudio.com/items?itemName=minodisk.bigquery-runner#keyboard-shortcuts) 🎉

**Comment by fabridamicelli** [comment]
> @fabridamicelli Published as [v1.21.12](https://marketplace.visualstudio.com/items?itemName=minodisk.bigquery-runner#keyboard-shortcuts) 🎉

Great!

**Pull request merged**
